### PR TITLE
Add system labels

### PR DESCRIPTION
**Pull request by tguichaoua**
Add labels for the systems, so it's possible to use `before` and `after`. For example, if some action has to be done just before the messages are sent.

`server_recv_packet_system` and `client_recv_packet_system` share the same label since I supposed that the client and the server plugins will never be both used at the same time.

`ServerSystem` and `ClientSystem` are enums even if they contains only one element, so they can be easily extended in the future if needed.

### CODE REVIEW

**Review by auderer — APPROVED** [review]
This would be great to have

**Comment by bacongobbler** [comment]
Sorry for the late response. Would you mind rebasing this PR against `main`?

**Comment by bacongobbler** [comment]
Looks great. Would you mind adding an example to demonstrate to newcomers how to use these system labels in practice? I'd prefer new examples so that we can keep the existing ones as a "getting started" guide. Thank you!

**Comment by bacongobbler** [comment]
ping

**Comment by tguichaoua** [comment]
Sorry for the delay, I completely forgot :sweat_smile:

**Review by bacongobbler — APPROVED** [review]

**Pull request merged**
